# Build settings

markdown: kramdown
permalink: none
plugins:             [jekyll-sitemap, jekyll-feed,  jekyll-seo-tag]

port: 4000

sass:
  sass_dir: assets/css
  style: :nested

# Customise atom feed settings (this is where Jekyll-Feed gets configuration information)

title:		           "Louis Snow"
description:	       "Art by Louis"
author:              ""
background-image: "url('/assets/background.jpg')"
url: "http://www.louissnow.com" 
